# Generated by Django 3.2.6 on 2021-09-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField(max_length=20)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('seqid', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcabahug.appointment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myappcabahug.user')),
            ],
        ),
    ]
